create table if not exists activities (
  id varchar unique primary key,
  name varchar,
  distance real,
  moving_time real,
  elapsed_time real,
  total_elevation_gain real,
  type varchar,
  start_date datetime,
  start_date_local datetime,
  timezone varchar,
  utc_offset int,
  gear_id varchar,
  average_speed real,
  max_speed real,
  average_cadence real,
  average_temp real,
  average_watts real,
  kilojoules real,
  average_heartrate real,
  max_heartrate real,
  elev_high real,
  elev_low real
);
